### ISSUE TITLE
UWP build Dll not found

### ISSUE THREAD

**Issue by egormor** [gujadot/RTSP_Unity_Plugin#1]
Hello. I'm trying to build and run your plugin with Unity WSA build. I've compiled dll and added it to Plugins folder, but when i'm trying to deploy it on my UWP device i'm getting:

DllNotFoundException: Unable to load DLL 'RTSPUnityPlugin': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SetRTSPTexture.SetTextureAsRTSPSink(String rtsp_uri, IntPtr texture, Int32 h, Int32 w)
   at SetRTSPTexture.CreateTextureAndPassToPlugin()
   at SetRTSPTexture.<Start>d__4.MoveNext()
   at UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator enumerator, IntPtr returnValueAddress)
   at UnityEngine.SetupCoroutine.$Invoke1(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: <Unknown> Line: 0)

Your plugin looks like what I exactly was looking for. Could you please add a short manual how to run it on Windows Store Build, please?

**Comment by tomitrescak** [comment]
Hi, looked sweet, but looking at internals, I'm pretty sure this never worked to start with
